### PR TITLE
https://github.com/PHPixie/Project/issues/34 - add doc blocks

### PR DESCRIPTION
**Pull request by Nayfania**
Add doc blocks for Conditions.php, Configs.php, Data.php, Database.php, Drivers.php, Exception.php, Loaders.php, Mappers.php, Maps.php, Models.php

### CODE REVIEW

**Comment by dracony** [comment]
Thanks! Thts really helpful! Can you try some other phpixie project maybe? Most of other ORM classes are rarely used by end users, so the docblocks won't matter much to them. In comparison components like Validate and Database could use better docblocks =)

**Comment by Nayfania** [comment]
Sure, no problem. :)

**Comment by dracony** [comment]
Thanks! Also visit us in the chat sometime =)

**Comment by Nayfania** [comment]
Yeah, I`m already there :)

**Pull request merged**
